apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  … 중략 …
      volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mynginxclaim
